import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { MenuBar, Footer } from '../components';
import Avatar from 'react-avatar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MyTailorApp </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <MenuBar />
      <div className={`container-fluid ${styles.home}`}>
        <header className='row text-center'>
          <h1>Your Best Value Preposition</h1>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
          <div style={{ margin: '20px 0' }}>
            <button>Join us!</button>
          </div>
          <div>
            <Image
              src='/tailor.png'
              alt='tailor'
              width={800}
              height={400}
              //   layout='fill'
            />
          </div>
        </header>

        <section
          className={`row text-center justify-content-center py-3 ${styles.primaryColor}`}
        >
          <div className='col-md-7 col-sm-1'>
            <h3>Our Services</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem
              ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
              tempor incididunt ut labore et dolore magna aliqua.
            </p>
          </div>
          <div>
            <button className={`${styles.button} mx-sm-1`}>Designer</button>
            <button className={`${styles.button}  mx-sm-1`}>Tailor</button>
            <button className={`${styles.button}  mx-sm-1`}>Shoes</button>
            <button className={`${styles.button}  mx-sm-1`}>Fabric</button>
            <button className={`${styles.button}  mx-sm-1`}>Accessories</button>
          </div>
        </section>
        <section
          className={`row justify-content-lg-center ${styles.feature_one} gx-0`}
        >
          <div
            className='col-sm-1 col-md-6 col-lg-6'
            style={{ position: 'relative' }}
          >
            <Image
              src='/section one.png'
              alt='section one'
              //   width={800}
              //   height={500}
              layout='fill'
            />
          </div>
          <div className='col-sm-1 col-md-6 col-lg-6'>
            <h3>Feature that is amazing</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <div>
              <a className={styles.buttonLink}>Learn More</a>
            </div>
          </div>
        </section>

        <section
          className={`row justify-content-lg-center ${styles.feature_two} gx-0`}
        >
          <div className='col-sm-1 col-md-6 col-lg-6'>
            <h3>Feature that is amazing</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <div>
              <a className={styles.buttonLink}>Learn More</a>
            </div>
          </div>
          <div
            className='col-sm-1 col-md-6 col-lg-6'
            style={{ position: 'relative' }}
          >
            <Image
              src='/section three.png'
              alt='section two'
              //   width={800}
              //   height={500}
              layout='fill'
            />
          </div>
        </section>

        <section
          className={`row justify-content-lg-center ${styles.feature_one} gx-0`}
        >
          <div
            className='col-sm-1 col-md-6 col-lg-6'
            style={{ position: 'relative' }}
          >
            <Image
              src='/section four.png'
              alt='section two'
              //   width={800}
              //   height={500}
              layout='fill'
            />
          </div>
          <div className='col-sm-1 col-md-6 col-lg-6'>
            <h3>Feature that is amazing</h3>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua.
            </p>
            <div>
              <a className={styles.buttonLink}>Learn More</a>
            </div>
          </div>
        </section>

        <section
          className={`row text-center justify-content-center mt-2 ${styles.five}`}
        >
          <div className='col-md-7 col-sm-1'>
            <h2>Your value preposition</h2>
            <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
              enim ad minim veniam,
            </p>
          </div>
          <div className={`row ${styles.avatars}`}>
            <div className='col'>
              <span>
                <Avatar name='Hermonie Grange' size='120' round={true} />
              </span>
              <h5>Hermione Granger</h5>
              <small>Designer</small>
            </div>
            <div className='col'>
              <span>
                <Avatar name='Harry Potter' size='120' round={true} />
              </span>
              <h5>Harry Potter</h5>
              <small>Tailor</small>
            </div>
            <div className='col'>
              <span>
                <Avatar name='Ron Weasly' size='120' round={true} />
              </span>
              <h5>Ron Weasley</h5>
              <small>Shoe Cobler</small>
            </div>
          </div>
        </section>

        <section
          className={`row justify-content-center text-center ${styles.six}`}
        >
          <div className='col-7'>
            <p>
              “Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
              eiusmod tempor incididunt.”
            </p>
          </div>
          <div className='col-7'>
            <span>
              <Avatar name='Victoria Kain' size='80' round={true} />
            </span>
            <h5>Victoria Kain</h5>
            <small>Kaduna</small>
          </div>
        </section>

        <section
          className={`row justify-content-center text-center align-items-center ${styles.seven}`}
        >
          <div className='col-sm-1 col-md-4'>
            <p>
              <strong> Ready to get started?</strong>
            </p>
            <p>Sign up or Contact us</p>
          </div>
          <div className='col-sm-1 col-md-4'>
            <button className={styles.button}>Get Started</button>
            <button className={styles.button}>Contact Us</button>
          </div>
        </section>
      </div>
      <Footer />
    </div>
  );
}
