import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { Navbar, Footer } from '../components';
import Avatar from 'react-avatar';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MyTailorApp </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <header>
        <h1>Your Best Value Preposition</h1>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </p>
        <div style={{ margin: '20px 0' }}>
          <button>Join us!</button>
        </div>
        <div>
          <Image src='/tailor.png' alt='tailor' width={800} height={400} />
        </div>
      </header>
      <section className={styles.one}>
        <h3>Our Services</h3>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum
          dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor
          incididunt ut labore et dolore magna aliqua.
        </p>
        <div>
          <button className={styles.button}>Designer</button>
          <button className={styles.button}>Tailor</button>
          <button className={styles.button}>Shoes</button>
          <button className={styles.button}>Fabric</button>
          <button className={styles.button}>Accessories</button>
        </div>
      </section>

      <section className={styles.two}>
        <div>
          <Image
            src='/section one.png'
            alt='section one'
            width={800}
            height={500}
          />
        </div>
        <div>
          <h3>Feature that is amazing</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
          <div>
            <a className={styles.buttonLink}>Learn More</a>
          </div>
        </div>
      </section>

      <section className={styles.three}>
        <div>
          <h3>Feature that is amazing</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
          <div>
            <a className={styles.buttonLink}>Learn More</a>
          </div>
        </div>
        <div>
          <Image
            src='/section three.png'
            alt='section two'
            width={800}
            height={500}
          />
        </div>
      </section>

      <section className={styles.four}>
        <div>
          <Image
            src='/section four.png'
            alt='section two'
            width={800}
            height={500}
          />
        </div>
        <div>
          <h3>Feature that is amazing</h3>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt ut labore et dolore magna aliqua.
          </p>
          <div>
            <a className={styles.buttonLink}>Learn More</a>
          </div>
        </div>
      </section>

      <section className={styles.five}>
        <h2>Your value preposition</h2>
        <p>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
          eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad
          minim veniam,
        </p>
        <div className={styles.avatars}>
          <div>
            <span>
              <Avatar name='Hermonie Grange' size='150' round={true} />
            </span>
            <h5>Hermione Granger</h5>
            <small>Designer</small>
          </div>
          <div>
            <span>
              <Avatar name='Harry Potter' size='150' round={true} />
            </span>
            <h5>Harry Potter</h5>
            <small>Tailor</small>
          </div>
          <div>
            <span>
              <Avatar name='Ron Weasly' size='150' round={true} />
            </span>
            <h5>Ron Weasley</h5>
            <small>Shoe Cobler</small>
          </div>
        </div>
      </section>

      <section className={styles.six}>
        <div>
          <p>
            “Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
            eiusmod tempor incididunt.”
          </p>
        </div>
        <div>
          <span>
            <Avatar name='Victoria Kain' size='80' round={true} />
          </span>
          <h5>Victoria Kain</h5>
          <small>Kaduna</small>
        </div>
      </section>

      <section className={styles.seven}>
        <div>
          <p>
            <strong> Ready to get started?</strong>
          </p>
          <p>Sign up or Contact us</p>
        </div>
        <div>
          <button className={styles.button}>Get Started</button>
          <button className={styles.button}>Contact Us</button>
        </div>
      </section>
      <Footer />
    </div>
  );
}
